# Generated by Django 3.2.7 on 2021-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0002_auto_20211009_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
