# Generated by Django 3.2.7 on 2021-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0003_category_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
