# Generated by Django 3.2.7 on 2021-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newgen', '0006_auto_20211110_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
